/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChatMessage = IDL.Record({
  'role' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'getChatHistory' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
  'registerPhone' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'setTopic' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChatMessage = IDL.Record({ 'role' : IDL.Text, 'message' : IDL.Text });
  
  return IDL.Service({
    'getChatHistory' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
    'registerPhone' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'setTopic' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };